export { Text } from './components/Text';
export { TextArea } from './components/TextArea';
export { Email } from './components/Email';
export { Submit } from './components/Submit';
export { Tel } from './components/Tel';
export { Number } from './components/Number';
export { Select } from './components/Select';
export { Radio } from './components/Radio';
export { Url } from './components/Url';
export { File } from './components/File';
export { Checkbox } from './components/Checkbox';
export { CheckboxGroup } from './components/CheckboxGroup';
export { Form } from './components/Form';
export { HoneyPot } from './components/HoneyPot';
// export { useMajiForm } from './lib/useMajiForm';
